name: spid-cie-oidc-php CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Create sample configuration
      run: cp -R config_sample/* config/ && ls -la config/

    - name: Create sample certificates
      run: cp -R cert_sample/* cert/ && ls -la cert/

    - name: Run PHP Code Sniffer
      run: php vendor/bin/phpcs --standard=PSR12 --warning-severity=0 lib www
      
    - name: Execute unit tests and create code coverage report
      run: phpdbg -qrr ./vendor/bin/phpunit --coverage-clover phpunit-clover.xml --coverage-text --coverage-html code_coverage_report
      
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: testphp-code-coverage-report
        path: code_coverage_report

    - name: Check code coverage score
      run: php vendor/bin/coverage-check phpunit-clover.xml 0
      
